version: '3.9'

services:
  together-db:
    image: postgres
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
  together-migration:
    build: ./jango
    command: python ./jango/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - together-db
  together-web:
    build: ./jango
    command: python ./jango/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - together-migration
      - together-db

volumes:
  postgres_data: